/**
 * Copyright (c) 2023-present Plane Software, Inc. and contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 * See the LICENSE file for details.
 */

// Usage: npx tsx packages/i18n/scripts/generate-resources.ts
// Reads:  src/locales/<lang>/<ns>.json
// Writes: src/core/resources.generated.ts
//
// Emits a static map of lazy locale loaders so that the bundler can resolve
// every locale/namespace at build time (no template-literal relative imports,
// no runtime path math).

import fs from "node:fs";
import path from "node:path";

const COPYRIGHT_HEADER = `/**
 * Copyright (c) 2023-present Plane Software, Inc. and contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 * See the LICENSE file for details.
 */`;

const PROJECT_ROOT = path.resolve(import.meta.dirname, "..");
const LOCALES_DIR = path.join(PROJECT_ROOT, "src", "locales");
const OUTPUT_FILE = path.join(PROJECT_ROOT, "src", "core", "resources.generated.ts");

function main() {
  const languages = fs
    .readdirSync(LOCALES_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .toSorted();

  const lines: string[] = [];
  lines.push(COPYRIGHT_HEADER);
  lines.push("");
  lines.push("// This file is auto-generated by scripts/generate-resources.ts — do not edit by hand.");
  lines.push("");
  lines.push("export const resourceLoaders: Record<string, () => Promise<{ default: unknown }>> = {");

  for (const lang of languages) {
    const localeDir = path.join(LOCALES_DIR, lang);
    const namespaces = fs
      .readdirSync(localeDir)
      .filter((f) => f.endsWith(".json"))
      .map((f) => path.basename(f, ".json"))
      .toSorted();
    for (const ns of namespaces) {
      lines.push(`  "${lang}/${ns}": () => import("../locales/${lang}/${ns}.json"),`);
    }
  }

  lines.push("};");
  lines.push("");

  fs.writeFileSync(OUTPUT_FILE, lines.join("\n"));
  // eslint-disable-next-line no-console
  console.log(`✓ Wrote ${OUTPUT_FILE}`);
}

main();
